service: marec-chat
 
provider:
  name: aws
  deploymentMethod: direct
  stage: dev
  region: us-west-2
  runtime: nodejs20.x
  websocketsApiName: ${self:service}-websocketApi
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
 
functions:
  - ${file(resources/functions.yml)}